### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by EmilJunker** [davidhealey/waistline#307]
The Crowdin translations are at 100% (have been for a while), so could you please merge the `l10n_master3` branch before pushing the next release?

Also, I noticed a few more strings that aren't localized yet:

- The new "Show Food Notes" option in settings 
- The error message "Please fill in this field" in the food and recipe editor
- The placeholders "Recipe Name" and "Cooking Instructions" in the recipe editor
- The text "Place a barcode inside the viewfinder rectangle to scan it" that is shown when scanning a barcode (according to the [docs](https://github.com/phonegap/phonegap-plugin-barcodescanner#using-the-plugin), this can be set via the `prompt` parameter)
- The placeholders "Category 5", "Category 6" etc. in the text fields in settings > diary > categories
- The message "Login Successfull" (which is spelled wrong BTW, it should be "Login Successful") in OFF and USDA integration settings

Finally, I noticed that when I switch from some other language back to English, parts of the app (including the app menu) aren't affected by the change until I restart the app. This only happens when switching to English and not with other languages.

**Comment by davidhealey** [comment]
Thanks, I'll implement fixes/updates before the next release

**Comment by davidhealey** [comment]
Mostly done https://github.com/davidhealey/waistline/commit/100e883c2617ff5094ba155f6a8ec16e14665bdc

> * The error message "Please fill in this field" in the food and recipe editor

I couldn't find this in the food editor. Any idea what line it's on?

> * The placeholders "Recipe Name" and "Cooking Instructions" in the recipe editor
> * The placeholders "Category 5", "Category 6" etc. in the text fields in settings > diary > categories

I haven't found a simple way to be able to localize placeholders yet. I think I'm going to have to roll my own solution for this. If you could make a separate issue for this one it would be handy.

> Finally, I noticed that when I switch from some other language back to English, parts of the app (including the app menu) aren't affected by the change until I restart the app. This only happens when switching to English and not with other languages.

I've added a prompt now to tell the user to restart the app to apply the changes.

**Comment by EmilJunker** [comment]
> > * The error message "Please fill in this field" in the food and recipe editor
> 
> I couldn't find this in the food editor. Any idea what line it's on?

I can't find it in the source code either. I guess it's an automatic thing handled by the OS. The message appears when I click inside a required text field but don't type anything. It probably uses the default system language, so it's not a big problem.

![Screenshot](https://user-images.githubusercontent.com/19289477/131216873-0a5c5b4d-5513-430b-aa27-2e98b56098bc.jpg)

> I haven't found a simple way to be able to localize placeholders yet.

Maybe just remove them? The text fields in question all have descriptive labels anyway.

**Comment by davidhealey** [comment]
> I guess it's an automatic thing handled by the OS.

Oh I think that's part of the UI framework. There probably is a way to localize it but I've not investigated it.

> Maybe just remove them? The text fields in question all have descriptive labels anyway.

Done

**Comment by EmilJunker** [comment]
> Done

Looks like you forgot to remove the "Category 7" placeholder :)

**Comment by davidhealey** [comment]
> Looks like you forgot to remove the "Category 7" placeholder :)

Done https://github.com/davidhealey/waistline/commit/6b8e71f25da5ab38cf4a69e12b3736db3da169e1

**Comment by EmilJunker** [comment]
Another small issue: the locale string `settings.statistics.title` in `locale-en.json` is currently set to "Statistics Settings" instead of just "Statistics" (which would be more in line with other settings section titles).

**Comment by EmilJunker** [comment]
> Oh I think that's part of the UI framework. There probably is a way to localize it but I've not investigated it.

According to the [Framework7 docs](https://framework7.io/docs/inputs.html), you can specify a custom error message by setting the `data-error-message` attribute (which I assume could also be done via JavaScript for a localized message string).
